openai_api_key = "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"

[connections.bryan_connection]
 # REQUIRED and should have data.records:read and schema.bases:read scopes
personal_access_token = "patqSsAIZe3wx7iDH.183881eeb822207cdec1ba4e0c0cef31ee77072e5764e34690e672ed920b17d2"
