openai_api_key = "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"

[connections.bryan_connection]
 # REQUIRED and should have data.records:read and schema.bases:read scopes
personal_access_token = "patQHWapaOd0sZXOt.6d3a213de1a04d43d32fbeaecf4377433c08d6776bf424239f57755e66fb68d6"
